spring.profiles.active: local
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://jwiryo-mysql-instance.cpnouctniwxz.ap-southeast-1.rds.amazonaws.com:3306/gameMatchTracker_DB?verifyServerCertificate=false&useSSL=true&useLegacyDatetimeCode=false
    username: jwiryo_admin
    password: 160192290395
    driver-class-name: com.mysql.cj.jdbc.Driver